groups:
- name: example
  rules:
  - record: job_service_rpc_durations_seconds_count_avg_rate5m
    expr: avg(rate(rpc_durations_seconds_count[5m])) by (job, service)
- name: alerttest
  rules:
  - alert: rpc_request_count
    expr: rate(rpc_request_count[1m]) > 0.1
    labels:
      test: count alert
    annotations:
      summary: Hi, counter